CREATE TABLE YD_RISK_IZLEM (
    -- 🔑 HASTA SABİT KİMLİK
    HASTA_ID          NUMBER NOT NULL,   -- her hasta için TEK
    HAFTA_NO          NUMBER NOT NULL CHECK (HAFTA_NO BETWEEN 1 AND 5),

    DOSYA_NO          NUMBER NOT NULL,
    PROTOKOL_NO       NUMBER NOT NULL,

    IZLEM_TARIHI      DATE NOT NULL,

    -- 🔹 SABİT (SADECE İLK HAFTA GİRİLECEK)
    GESTASYON_HAFTASI NUMBER,
    DOGUM_KILOSU_GR   NUMBER,
    DOGUM_BOYU_CM     NUMBER,
    DOGUM_BAS_CEVRESI NUMBER,

    -- 🔹 YÜKSEK RİSK
    YR_28_HAFTA       VARCHAR2(1) DEFAULT 'F' CHECK (YR_28_HAFTA IN ('T','F')),
    YR_1000_GR        VARCHAR2(1) DEFAULT 'F',
    YR_NEK_GIS        VARCHAR2(1) DEFAULT 'F',
    YR_KONJ_GIS       VARCHAR2(1) DEFAULT 'F',

    -- 🔹 ORTA RİSK
    OR_28_31_HAFTA    VARCHAR2(1) DEFAULT 'F',
    OR_IUGR           VARCHAR2(1) DEFAULT 'F',
    OR_1000_1500_GR   VARCHAR2(1) DEFAULT 'F',
    OR_KONJ_BESLENME  VARCHAR2(1) DEFAULT 'F',

    -- 🔹 DÜŞÜK RİSK
    DR_32_35_HAFTA    VARCHAR2(1) DEFAULT 'F',
    DR_IUGR_35        VARCHAR2(1) DEFAULT 'F',
    DR_TERM           VARCHAR2(1) DEFAULT 'F',

    -- 🔹 SEÇİLEN RİSK (tek değer)
    RISK_SEVIYE       VARCHAR2(10), -- YUKSEK / ORTA / DUSUK

    -- 🔹 İHTİYAÇ TESPİTİ (çoklu)
    IHT_2_HAFTA_KILO  VARCHAR2(1) DEFAULT 'F',
    IHT_15_KAYIP      VARCHAR2(1) DEFAULT 'F',
    IHT_10G_KAZANIM   VARCHAR2(1) DEFAULT 'F',
    IHT_NEK_CERRAHI   VARCHAR2(1) DEFAULT 'F',

    DOKTOR_ADI        VARCHAR2(100),
    KAYIT_TARIHI      DATE DEFAULT SYSDATE,

    CONSTRAINT PK_YD_RISK PRIMARY KEY (HASTA_ID, HAFTA_NO)
);
