CREATE SEQUENCE SEQ_YD_RISK_IZLEM
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;



CREATE OR REPLACE TRIGGER TRG_YD_RISK_IZLEM_BI
BEFORE INSERT ON YD_RISK_IZLEM
FOR EACH ROW
BEGIN
  IF :NEW.HASTA_ID IS NULL THEN
    SELECT SEQ_YD_RISK_IZLEM.NEXTVAL
      INTO :NEW.HASTA_ID
      FROM DUAL;
  END IF;
END;
/
